config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, :address, presence: :true
  validates :category, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5).to_a }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for (@restaurant) do |f| %>

  <div class="form-inputs">
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category %>
<%= f.input :reviews %>
<%= f.submit 'submit', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= restaurant.phone_number %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= restaurant.category %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= restaurant.reviews %>
  </p>

</div>

app/views/restaurants/edit.html.erb
<div class="card m-5 p-5">
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>All restaurants</h1>
      <ul class="list-group mb-3">
        <% @restaurants.each do |restaurant| %>
          <li class="list-group-item">
            <%= link_to restaurant.name, restaurant_path(restaurant) %>
          </li>
        <% end %>
      </ul>
      <%= link_to "Add a new Restaurant", new_restaurant_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new restaurant</h1>
      <%= simple_form_for @restaurant do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category, collection: Restaurant::CATEGORIES %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1><%= @restaurant.name %></h1>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th scope="row">Address</th>
            <td><%= @restaurant.address %></td>
          </tr>
          <tr>
            <th scope="row">Phone Number</th>
            <td><%= @restaurant.phone_number %></td>
          </tr>
          <tr>
            <th scope="row">Category</th>
            <td><%= @restaurant.category %></td>
          </tr>
        </tbody>
      </table>

      <div class="list-group">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item">
            <small>
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <i class="fa-solid fa-star"></i>
                <% else %>
                  <i class="fa-regular fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            </small>
            <p><%= review.content %></p>
          </li>
        <% end %>
      </div>

      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :rating, collection: 0..5 %>
        <%= f.input :content%>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <%= link_to "See all restaurants", restaurants_path %>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="card m-5 p-5">
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<div id="review">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", review %>
    </p>
  <% end %>
</div>
<div class="btn btn-danger">
<%= link_to "New review", reviews_new_path, class: "link_to" %>
</div>

</div>

app/views/reviews/new.html.erb
<h1>Reviews for <%= @restaurant.name %></h1>

<!-- <form action=""> -->
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary"%>
<% end %>